disabled = false
locale = "en"
label = "English"
weight = 1
title = "Artin Zarei's Logs"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

  [params.author]
  links = [ ]

["params.author"]
name = "Artin Zarei"
email = "artin.zarei2004@gmail.com"
bio = "I am just another Computer Science _(and apparently CE)_ student, sharing my adventures and interests on another Japanese-looking static-site generator. Welcome to my realm!"
image = "me.jpg"
imageQuality = ""
